package json;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BTN".
 */
public class Btn {

    @Override
	public String toString() {
		return "Btn [id=" + id + ", name=" + name + ", state=" + state + "]";
	}

	private Long id;
    private String name;
    private Integer state;

    public Btn() {
    }

    public Btn(Long id) {
        this.id = id;
    }

    public Btn(Long id, String name, Integer state) {
        this.id = id;
        this.name = name;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
